version: '3'

services:

  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodb
    restart: unless-stopped
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes: 
      - ./database-data:/data/db

  mongo-express:
    image: mongo-express:latest 
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb 

  api:
    build: .
    command: yarn start:${API_START_ARG}
    restart: on-failure
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - micro-nest-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management           
    ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API    
      - 5673:5672      
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
        RABBITMQ_DEFAULT_USER: adminmq
        RABBITMQ_DEFAULT_PASS: passwordmq
    restart: always

networks:
  micro-nest-network:
  