version: '3'

services:
  postgres:
    env_file:
      - .env
    image: postgres
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-micro-nest-data:/var/lib/postgresql/data
    networks:
      - micro-nest-network

  pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - micro-nest-network

  api:
    build: .
    command: yarn start:${API_START_ARG}
    restart: on-failure
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - micro-nest-network

volumes:
  postgres-micro-nest-data:
    driver: local
networks:
  micro-nest-network: